### ISSUE TITLE
Impossible de voter T2+

### ISSUE THREAD

**Issue by Lesterpig** [Lesterpig/openparty-mafia#15]
Pour les villageois (mafiosi ?)

**Comment by Lesterpig** [comment]
Le bug semble ne pas se produire dans toutes les circonstances. A reproduire.

**Comment by HemnesLGeL** [comment]
J'essaie de reproduire demain
EDIT : Je ne reproduis pas

**Comment by Lesterpig** [comment]
Je laisse l'issue pour le moment, si d'ici un mois on a pas reproduit le bug, il sera considéré comme **absent**. Bizarre quand même...
