### ISSUE TITLE
Affichage de la composition une fois la partie lancée

### ISSUE THREAD

**Issue by Lesterpig** [Lesterpig/openparty-mafia#16]
L'afficher une fois en haut suffit-il ?
Faut-il toujours l'afficher ?

**Comment by HemnesLGeL** [comment]
Je pense qu'il est nécessaire de l'afficher, avec de nombreux joueurs et plusieurs spés, on peut s'y perdre rapidement. ^^ 
L'afficher à côté de "un mafiosi est parmi vous" devrait suffire

**Comment by MinervaJoke** [comment]
Ouep, j'suis pour qu'elle reste affichée ! 
Juste une petite liste dans un coin, c'est pas trop dérangeant !
