### ISSUE TITLE
Le docteur ne peut protéger qu'une seule fois

### ISSUE THREAD

**Issue by HemnesLGeL** [Lesterpig/openparty-mafia#17]
Impossibilité de protéger plus d'une nuit, sûrement une erreur de copier-coller lors de la création du rôle.

**Comment by Lesterpig** [comment]
Dans la dernière version ?

J'ai fait un correctif hier soir. Le bug se produit il systématiquement ?

**Comment by HemnesLGeL** [comment]
Au temps pour moi, je ne testais pas sur la dernière version !

**Comment by Lesterpig** [comment]
N'hésite pas à rouvrir si le problème se reproduit ;-)
