### ISSUE TITLE
Ajout du terroriste

### ISSUE THREAD

**Issue by HemnesLGeL** [Lesterpig/openparty-mafia#18]
- Le terroriste peut choisir de faire un attentat suicide et d'emporter le joueur de son choix dans sa mort
- Il joue la nuit, sa mort et celle de la victime collatérale surviennent au début du jour 
- Si l'un des deux joueurs impliqué dans l'attentat est protégé par le Docteur, il survivra 

Variantes possibles : 
- Le terroriste tue ses voisins dans l'attentat (ou un de ses voisins ?)
- Le terroriste utilise son pouvoir en pleine journée à n'importe quel moment du débat.

**Comment by Lesterpig** [comment]
Variante :
- Le terroriste utilise son pouvoir en pleine journée à n'importe quel
  moment du débat.

**Comment by Lesterpig** [comment]
Correctifs sur le rôle (pour plus de RP et de possibilités de gameplay, à discuter !)
- Du côté des mafieux
- Si le docteur protège le terroriste, **rien ne se passe**
- Si le docteur protège la cible, **la protection n'est pas effective**

**Comment by HemnesLGeL** [comment]
Je voyais plus le terroriste du côté des innocents, comme un joueur pouvant se sacrifier pour éliminer un méchant mafieux. ^^ Dans une variante peut-être ?

**Comment by Lesterpig** [comment]
Deux types de terroristes, pourquoi pas :D En général, c'est méchant ce genre de personnes, du coup intuitivement je le met côté mafia. 
Et puis, c'est tellement diabolique : la mafia le connaît, mais lui ne connaît pas la mafia .. gros risque de tuer un mafieux en s'explosant, j'adore :)

**Comment by HemnesLGeL** [comment]
Tiens, d'ailleurs ça peut faire une autre variante : le terroriste est solitaire et décide d'avantager tel ou tel camp selon son humeur !

**Comment by qsigit** [comment]
Après, on associe souvent le terrorisme au fanatisme. Le personnage pourrait se reposer sur ça après tout.

**Comment by Lesterpig** [comment]
Oui, et puis chacun joue comme il veut :)
