### ISSUE TITLE
Partie avec un nom vide

### ISSUE THREAD

**Issue by qsigit** [Lesterpig/openparty-mafia#25]
Est-ce normal que l'on puisse faire des parties au nom vide ou est-ce un oubli de codage ? ^^

**Comment by Lesterpig** [comment]
Pour moi ça ne me pose aucun problème ;)
C'est gênant ?

**Comment by qsigit** [comment]
Du tout mais ça me semblait curieux. Et puis, ça laisse des blancs à certains endroits. =p

**Comment by Lesterpig** [comment]
Effectivement ;)
Du coup ça concerne plutôt le moteur du jeu (https://github.com/Lesterpig/openparty) qui permet des salons sans nom. Merci pour la remarque en tout cas :)
