### ISSUE TITLE
Ajout du dentiste

### ISSUE THREAD

**Issue by HemnesLGeL** [Lesterpig/openparty-mafia#29]
- Le dentiste est un villageois
- Une fois dans la partie, il peut oublier un outil dans la bouche du joueur et ainsi le bâillonner.

Variante possible :
- On ne sait pas qui est bâillonné
- 1 fois sur 20, le joueur s'étouffe avec l'outil resté dans sa bouche et meurt à la fin du tour

J'ai commencé à le coder, j'ai bientôt terminé.

**Comment by Lesterpig** [comment]
Sympa !
Petite remarque : si possible, essaye de mettre tout le code du dentiste (hors paramètres) dans un seul fichier. Si tu n'y arrive pas, c'est pas grave j'essaierai de faire plus compact. C'est juste histoire de bien isoler les rôles entre eux pour garder un code sain.

**Comment by Lesterpig** [comment]
@HemnesLGeL Hello ! Besoin d'aide pour ce rôle ? ;)
