### ISSUE TITLE
Instabilité serveur de démonstration

### ISSUE THREAD

**Issue by Lesterpig** [Lesterpig/openparty-mafia#30]
Le serveur de démonstration http://mafia.lesterpig.com subit actuellement de très nombreuses coupures réseau.

Le problème provient du **fournisseur d'accès** et risque de ne pas être résolu avant quelques jours.

Si quelqu'un dispose d'un serveur mafia pouvant remplacer le serveur de demo temporairement, qu'il n'hésite pas à l'indiquer ;) Merci !

**Comment by HemnesLGeL** [comment]
Mafia est uniquement en local pour ma part, désolé. ^^'

**Comment by Lesterpig** [comment]
Je viens de louer un petit serveur supplémentaire en attendant : http://spare.lesterpig.com

**Comment by Lesterpig** [comment]
La situation semble stable sur le serveur classique, je surveille.

**Comment by Lesterpig** [comment]
Rechuté

**Comment by Lesterpig** [comment]
Revenu, je surveille toujours.

**Comment by Lesterpig** [comment]
Toujours pas revenu, ça devrait être bon la semaine prochaine.
