### ISSUE TITLE
Déconnexion du MDJ

### ISSUE THREAD

**Issue by HemnesLGeL** [Lesterpig/openparty-mafia#31]
- [x] Si le MDJ met un temps de débat infini et quitte la partie, les joueurs restent coincés dans une phase de jeu sans fin.
- [x] On peut toujours envoyer un message au MDJ après sa déconnexion
- [x] Si le MDJ désactive la victoire automatique et quitte la partie, cette première ne se réactive pas.

**Comment by Lesterpig** [comment]
Je corrige, merci du signalement

**Comment by Lesterpig** [comment]
~~En attente de https://github.com/Lesterpig/openparty/issues/25~~ OK

**Comment by Lesterpig** [comment]
C'est tout bon, ça sera validé quand Openparty passera en version 0.1.2 (sous peu)
