### ISSUE TITLE
Aligner les informations des joueurs

### ISSUE THREAD

**Issue by Lesterpig** [Lesterpig/openparty-mafia#34]
Sur le côté, l'alignement est très moyen entre pseudo, rôle, votes...
A rectifier.

**Comment by qsigit** [comment]
Avec Bootstrap, il doit être possible de faire des blocs avec les éléments dedans correctement alignés.
A voir.

**Comment by Lesterpig** [comment]
Ouep, je pensais à un truc du genre :)
