### ISSUE TITLE
Désynchronisation des compteurs

### ISSUE THREAD

**Issue by mens-sana** [Lesterpig/openparty-mafia#41]
J'ai remarqué en ouvrant plusieurs onglets sur la même partie que les compteurs se désynchronisent complètement. On arrive rapidement à des écarts d'une minute ou plus ! La raison c'est que Chrome impose une exécution plus lente de l'horloge dans les tabs masqués (ou qui sont dans une fenêtre minimisée). On peut se dire que les joueurs n'auront qu'un seul tab par partie, mais ya quand même beaucoup de cas où ça peut arriver :
- Le joueur change de tab pendant la partie. Ca arrive assez souvent, surtout quand on utilise un autre site / programme pour le chat vocal par exemple. On a aussi tendance à changer de tab quand on est mort, c'est moins dérangeant mais ça reste dommage que l'affichage bug.
- Un autre programme impose au navigateur de se minimiser ou d'ouvrir un autre tab. Et oui ces fichus popups...
- Un autre processus ralentit l'exécution du navigateur. C'est le fond de la question, l'affichage dépend des ressources de chacun.

Pour cette raison, je trouve ça toujours délicat qu'un même timer soit dupliqué chez chaque client.

Est ce que ce ne serait pas mieux d'avoir un seul timer pour la room, et exécuté par le serveur ?

On pourrait soit envoyer un message à chaque tic, soit attacher un événement à la modification de la valeur du timer de la room pour déclencher le nouvel affichage. Comme ça ceux qui rament rattraperont leur retard.

Aussi, comme on prévoit qu'un joueur peut se reconnecter après une déco, ça facilite les choses. Plutôt que de faire une soustraction hasardeuse pour démarrer son timer à la bonne valeur, il récupèrera juste les messages / événements comme les autres dès qu'il se reco.

**Comment by Lesterpig** [comment]
Effectivement, j'ai remarqué ce problème également. Ce n'est pas très critique, car seul l'affichage des joueurs est perturbé: le serveur maintient un timer rigoureux, qui n'est pas altéré par les joueurs.

Générer un tick par seconde est bien trop gourmand en CPU et bande passante pour le serveur. Par contre, on peut envisager une synchro toutes les 60 secondes par exemple :-)

Quoi qu'il en soit, cette issue concerne plutôt le framework Openparty. Je vais fermer celle-ci, mais merci d'avoir remonté le problème !

**Comment by mens-sana** [comment]
Mais c'est important. Si tu as changé de tab tu ne sais plus jusqu'à quand tu peux voter...

Par exemple là je viens d'avoir le problème. On fait une partie avec MDJ et des rôles non codés. J'étais Altruiste. Si jamais j'étais voté, je comptais au moins me suicider avant d'être lynché. Je n'ai pas pensé au fait que j'avais lu un peu les rôles sur gdoc pendant le débat. Du coup j'ai été lynché alors qu'il me restait 30 secondes au compteur et sans pouvoir utiliser mon pouvoir....

Si on implémente ce genre de rôle, ça fera pareil... Avec les événements je pense que tu peux t'en sortir. Pourquoi pas un seul timer global pour tout Openparty, qui modifie tous les timers des rooms en même temps, et les clients écoutent cet événement.

**Comment by mens-sana** [comment]
J'ai trouvé un trick plutôt sympa sur un forum, il s'agit d'afficher le temps réel écoulé et pas l'itération du compteur :

function loop()
{
now = new Date().getTime();
var time = now - start;

// output time

if (time <= 0)
// end
}  

var now, start = new Date().getTime(), interval = 1000;
setTimeout(loop, interval);

Comme ça même si on est pas sûr que la boucle aura un intervalle régulier, l'affichage restera plus ou moins correct.

**Comment by Lesterpig** [comment]
Ah yes ! Ça me paraît une excellente solution pas trop complexe :-)
Attention, le client est pas forcément à l'heure du serveur par contre...
