### ISSUE TITLE
Rendre le tchat plus lisible

### ISSUE THREAD

**Issue by Lesterpig** [Lesterpig/openparty-mafia#6]
En rajoutant des icônes, des boîtes pour séparer...

**Comment by HemnesLGeL** [comment]
J'ai essayé d'améliorer ça (cf pull request), je continue demain (avec ajout de boites pour le tour de mafia notamment)

**Comment by Lesterpig** [comment]
Ok, merci ! 
Je vais regarder et fusionner toutes tes modifications à partir de demain.

As tu réussi à installer ton propre serveur ?
